import React from 'react';
import {
  Globe,
  Recycle,
  Trophy,
  Leaf,
  Target,
  Sparkles,
  User,
  Brain,
  Gamepad2,
  Flame,
  Award,
  Gift,
  BarChart3,
  Camera,
  Mail,
  Lock,
  Key,
  AlertTriangle,
  CheckCircle,
  XCircle,
  FileText,
  Zap,
  Droplets,
  Bike,
  Lightbulb,
  TreePine,
  Factory,
  BookOpen,
  Trash2,
  Shirt,
  Smartphone,
  Coffee,
  Utensils,
  Bus,
  ShoppingBag,
  Plug,
  CloudRain,
  Store,
  Footprints,
  BottleWine,
  Palette,
  Mountain,
  Mic,
  GraduationCap,
  FlaskConical,
  LeafyGreen,
  Heart,
  Bot,
  Thermometer,
  BookMarked,
  Settings,
  Save,
  Search,
  Star,
  TrendingUp,
  Gauge,
  ChevronRight,
  Wine,
  Battery,
  Waves,
  HandHeart,
  Salad,
  Sparkle,
  Car,
} from 'lucide-react';

const ICON_MAP = {
  globe: Globe,
  earth: Globe,
  recycle: Recycle,
  trophy: Trophy,
  leaf: Leaf,
  target: Target,
  sparkles: Sparkles,
  user: User,
  brain: Brain,
  gamepad: Gamepad2,
  flame: Flame,
  award: Award,
  gift: Gift,
  chart: BarChart3,
  camera: Camera,
  mail: Mail,
  lock: Lock,
  key: Key,
  warning: AlertTriangle,
  success: CheckCircle,
  error: XCircle,
  file: FileText,
  zap: Zap,
  droplets: Droplets,
  bike: Bike,
  lightbulb: Lightbulb,
  tree: TreePine,
  factory: Factory,
  book: BookOpen,
  trash: Trash2,
  shirt: Shirt,
  smartphone: Smartphone,
  coffee: Coffee,
  utensils: Utensils,
  bus: Bus,
  bag: ShoppingBag,
  plug: Plug,
  rain: CloudRain,
  store: Store,
  footprints: Footprints,
  bottle: BottleWine,
  palette: Palette,
  mountain: Mountain,
  mic: Mic,
  graduation: GraduationCap,
  flask: FlaskConical,
  leafy: LeafyGreen,
  heart: Heart,
  bot: Bot,
  thermometer: Thermometer,
  bookmark: BookMarked,
  settings: Settings,
  save: Save,
  search: Search,
  star: Star,
  trending: TrendingUp,
  gauge: Gauge,
  chevron: ChevronRight,
  wine: Wine,
  paper: FileText,
  battery: Battery,
  beach: Waves,
  handheart: HandHeart,
  salad: Salad,
  sparkle: Sparkle,
  car: Car,
  plastic: Recycle,
  metal: Wine,
  glass: BottleWine,
  papel: FileText,
  organico: Leaf,
  eletronico: Smartphone,
};

/**
 * Ícone unificado do app. Use o nome em minúsculas (ex: "globe", "trophy").
 * @param {string} name - Nome do ícone (chave do ICON_MAP)
 * @param {number} size - Tamanho em px (default 24)
 * @param {string} className - Classes Tailwind
 */
export function AppIcon({ name, size = 24, className = '' }) {
  const key = (name || '').toLowerCase().replace(/\s+/g, '');
  const IconComponent = ICON_MAP[key] || Globe;
  return <IconComponent size={size} className={className} aria-hidden />;
}

export { ICON_MAP };
export default AppIcon;
